spring:

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_db
    username: sa
    password: password

  h2:
    console:
      enabled: true
